[ids]
*

[main]
# ----- Left side modifiers -----
leftalt      = leftcontrol
leftmeta     = leftalt
leftcontrol  = leftmeta

# Caps Lock: tap = Esc, hold = Shift + Super + Alt
#capslock = overload(esc, leftshift+leftmeta+leftalt+noop)
#capslock = macro(S-A-M)


# ----- Right side modifiers -----
#rightalt     = rightcontrol
#sysrq        = leftalt
#rightcontrol = rightalt

capslock = overload(symbols, esc)
[symbols]
# Define what happens when held with other keys
# Example: hold capslock + a → Shift+Alt+Super+a
1 = S-A-M-1
2 = S-A-M-2
3 = S-A-M-3
4 = S-A-M-4
5 = S-A-M-5
6 = S-A-M-6
7 = S-A-M-7
8 = S-A-M-8
9 = S-A-M-9
0 = S-A-M-0
q = S-A-M-q
w = S-A-M-w
e = S-A-M-e
r = S-A-M-r
t = S-A-M-t
y = S-A-M-y
u = S-A-M-u
i = S-A-M-i
o = S-A-M-o
p = S-A-M-p
a = S-A-M-a
s = S-A-M-s
d = S-A-M-d
f = S-A-M-f
g = S-A-M-g
h = S-A-M-h
j = S-A-M-j
k = S-A-M-k
l = S-A-M-l
z = S-A-M-z
x = S-A-M-x
c = S-A-M-c
v = S-A-M-v
b = S-A-M-b
n = S-A-M-n
m = S-A-M-m
, = S-A-M-,
. = S-A-M-.
enter = S-A-M-enter
